DROP TABLE IF EXISTS TORYBURCH;
CREATE TABLE TORYBURCH (
	ROW_ID INTEGER PRIMARY KEY AUTOINCREMENT, 
	CATEGORY VARCHAR(100), 
	NAME VARCHAR(100), 
	STANDARD_PRICE VARCHAR(100), 
	SALES_PRICE VARCHAR(100), 
	DESC VARCHAR(100), 
	URL VARCHAR(100), 
	IMG_URL VARCHAR(100), 
	CREATED DATE, 
	LAST_UPD DATE
);