--DROP TABLE IF EXISTS TORY_PROD;
--CREATE TABLE TORYBURCH (
--	ROW_ID INTEGER PRIMARY KEY AUTOINCREMENT,
--	CATEGORY VARCHAR(100),
--	NAME VARCHAR(100),
--	STANDARD_PRICE VARCHAR(100),
--	SALES_PRICE VARCHAR(100),
--	DESC VARCHAR(100),
--	URL VARCHAR(100),
--	IMG_URL VARCHAR(100),
--	CREATED DATE,
--	LAST_UPD DATE
--);


DROP TABLE IF EXISTS TORY_PROD;
CREATE TABLE TORY_PROD (
	ROW_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	CATEGORY VARCHAR(100),
	CATEGORY_URL VARCHAR(100),
	NAME VARCHAR(100),
	DESC VARCHAR(100),
	STANDARD_PRICE VARCHAR(100),
	SALES_PRICE VARCHAR(100),
	URL VARCHAR(100),
	IMG_URL VARCHAR(100),
	ALT_IMG_URL VARCHAR(100),
	ALT_IMG_DESC VARCHAR(100),
	STATUS VARCHAR(100),	-- EXPIRED, ACTIVE
	CREATED DATE,
	LAST_UPD DATE
);

DROP TABLE IF EXISTS TORY_PRICE;
CREATE TABLE TORY_PRICE (
	ROW_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	PAR_ROW_ID INTEGER,
	STANDARD_PRICE VARCHAR(100),
	SALES_PRICE VARCHAR(100),
	CREATED DATE,
	LAST_UPD DATE
);


--alter table TORY_PROD add ALT_IMG_DESC VARCHAR(100);